version: '2'

services:
  covid_social_distancing_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: covid_social_distancing/web:latest
    container_name: "covid_social_distancing"
    ports:
      - "5083:80"
    working_dir: /app
    environment:
      DB_HOST: db:3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: database
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

volumes:
    db_data: